swagger: '2.0'
info:
  description: NGM Alarm Ingest
  version: 1.0.0
  title: NGM Azure CAM Ingest
  contact:
    email: neil.middleton@tr.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: ngmalarmingest.azurewebsites.net
basePath: /api
tags:
  - name: alarm
    description: Everything about your Alarm
    externalDocs:
      description: Find out more
      url: 'https://thehub.thomsonreuters.com/docs/DOC-851597'
schemes:
  - http
paths:
  /ngm-alarm-ingest:
    post:
      tags:
        - alarm
      summary: Send an alarm
      description: ''
      operationId: sendAlarm
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Alarm object that needs to be sent
          required: true
          schema:
            $ref: '#/definitions/Alarm'
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
      security:
        - api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header
definitions:
  Alarm:
    type: object
    properties:
      reporter:
        type: string
        description: The registered system reporting the alarm
      end_point_id:
        type: string
        description: The ID of the host/application
      category:
        type: string
        description: What specific type of problem being reported?
      message:
        type: string
        description: The message to the operator describing the problem
      informer:
        type: string
        description: The host sending this alarm
      status:
        type: string
        description: Status (severity) if the alarm
        enum:
          - CRITICAL
          - WARNING
          - OK
      alarm_type:
        type: string
        description: What entity is sending the alarm
        enum:
          - host
          - application
    example:
      reporter: sensu
      end_point_id: c844ctsbmnpp1
      alarm_type: host
      status: CRITICAL
      category: azure_aws_2
      message: Ignore this alarm azure_aws_2
      informer: c844ctsbmnpp1
      occurred_at: '2018-03-20T14:00:45Z'
      context:
        environment: Pre-Production
externalDocs:
  description: Find out more about CAM
  url: >-
    https://thehub.thomsonreuters.com/groups/compass-monitoring-alarm-management-cam
